# domain/factories/work_history_entry_factory.py
from typing import Optional, Union
from datetime import date
from domain.contexts.employee_management.value_objects.work_history_entry import WorkHistoryEntry
from domain.models.EmployeeWorkHistoryModel import EmployeeWorkHistoryModel, WorkHistoryStatus
from utilities.logging_factory import get_logger

logger = get_logger("heijunka.factories.work_history_entry")

class WorkHistoryEntryFactory:
    """
    Factory for creating WorkHistoryEntry domain entities from EmployeeWorkHistoryModel database models
    and vice versa.
    """

    @staticmethod
    def create_from_model(model: EmployeeWorkHistoryModel) -> WorkHistoryEntry:
        """
        Create a WorkHistoryEntry domain entity from an EmployeeWorkHistoryModel.

        Args:
            model: The database model to convert.

        Returns:
            A WorkHistoryEntry domain entity.
        """
        logger.debug(
            f"Converting EmployeeWorkHistoryModel [id={model.id}] to domain WorkHistoryEntry",
            extra={
                "event_type": "model_to_domain_conversion",
                "entity_id": model.id,
                "employee_id": model.employee_id,
                "workstation_id": model.station_id
            }
        )

        return WorkHistoryEntry(
            employee_id=model.employee_id,
            workstation_id=model.station_id,
            worked_date=model.worked_date,
            work_period=model.work_period,
            end_flag=model.end_flag
        )

    @staticmethod
    def create_from_entity(entity: WorkHistoryEntry) -> EmployeeWorkHistoryModel:
        """
        Create an EmployeeWorkHistoryModel database model from a WorkHistoryEntry domain entity.

        Args:
            entity: The domain entity to convert.

        Returns:
            An EmployeeWorkHistoryModel database model.
        """
        logger.debug(
            "Converting WorkHistoryEntry domain entity to model",
            extra={
                "event_type": "domain_to_model_conversion",
                "employee_id": entity.employee_id,
                "workstation_id": entity.workstation_id,
                "worked_date": entity.worked_date.isoformat() if hasattr(entity.worked_date, 'isoformat') else str(entity.worked_date),
                "work_period": entity.work_period
            }
        )

        return EmployeeWorkHistoryModel(
            employee_id=entity.employee_id,
            station_id=entity.workstation_id,
            worked_date=entity.worked_date,
            work_period=entity.work_period,
            end_flag=entity.end_flag,
            status=WorkHistoryStatus.REGULAR  # Default status
        )

    @staticmethod
    def create_with_all_fields(
        employee_id: int, 
        workstation_id: int, 
        worked_date: date, 
        work_period: int, 
        end_flag: bool = False,
        schedule_id: Optional[int] = None,
        status: Optional[WorkHistoryStatus] = None,
        is_generated: bool = False,
        is_temporary: bool = False
    ) -> EmployeeWorkHistoryModel:
        """
        Create an EmployeeWorkHistoryModel with all available fields.

        Args:
            employee_id: The ID of the employee
            workstation_id: The ID of the workstation
            worked_date: The date of the work
            work_period: The period of the day
            end_flag: Whether this is the end of a sequence
            schedule_id: Optional ID of the schedule this assignment belongs to
            status: The status of the work history entry (REGULAR, GENERATED, TEMPORARY, GENERATED_TEMPORARY)
            is_generated: (Deprecated) Whether this entry was generated by the scheduler
            is_temporary: (Deprecated) Whether this is a temporary assignment

        Returns:
            An EmployeeWorkHistoryModel database model.
        """
        logger.debug(
            "Creating EmployeeWorkHistoryModel with all fields",
            extra={
                "event_type": "model_creation",
                "employee_id": employee_id,
                "workstation_id": workstation_id,
                "worked_date": worked_date.isoformat() if hasattr(worked_date, 'isoformat') else str(worked_date),
                "work_period": work_period
            }
        )

        # Determine status based on parameters
        if status is not None:
            # Use provided status
            entry_status = status
        else:
            # Determine status from boolean flags for backward compatibility
            if is_generated and is_temporary:
                entry_status = WorkHistoryStatus.GENERATED_TEMPORARY
            elif is_generated:
                entry_status = WorkHistoryStatus.GENERATED
            elif is_temporary:
                entry_status = WorkHistoryStatus.TEMPORARY
            else:
                entry_status = WorkHistoryStatus.REGULAR

        return EmployeeWorkHistoryModel(
            employee_id=employee_id,
            station_id=workstation_id,
            schedule_id=schedule_id,
            worked_date=worked_date,
            work_period=work_period,
            end_flag=end_flag,
            status=entry_status
        )

    @staticmethod
    def update_model_from_entity(model: EmployeeWorkHistoryModel, entity: WorkHistoryEntry) -> None:
        """
        Update an EmployeeWorkHistoryModel with values from a WorkHistoryEntry entity.

        Args:
            model: The database model to update.
            entity: The domain entity with updated values.
        """
        logger.debug(
            f"Updating EmployeeWorkHistoryModel [id={model.id}] from domain entity",
            extra={
                "event_type": "model_update",
                "entity_id": model.id,
                "employee_id": entity.employee_id,
                "workstation_id": entity.workstation_id
            }
        )

        # Check for significant changes and log them
        if model.employee_id != entity.employee_id:
            logger.info(
                "Changing work history employee",
                extra={
                    "event_type": "work_history_field_change",
                    "entity_id": model.id,
                    "field": "employee_id",
                    "old_value": model.employee_id,
                    "new_value": entity.employee_id
                }
            )

        if model.station_id != entity.workstation_id:
            logger.info(
                "Changing work history workstation",
                extra={
                    "event_type": "work_history_field_change",
                    "entity_id": model.id,
                    "field": "station_id",
                    "old_value": model.station_id,
                    "new_value": entity.workstation_id
                }
            )

        if model.worked_date != entity.worked_date:
            logger.info(
                "Changing work history date",
                extra={
                    "event_type": "work_history_field_change",
                    "entity_id": model.id,
                    "field": "worked_date",
                    "old_value": model.worked_date.isoformat() if hasattr(model.worked_date, 'isoformat') else str(model.worked_date),
                    "new_value": entity.worked_date.isoformat() if hasattr(entity.worked_date, 'isoformat') else str(entity.worked_date)
                }
            )

        if model.work_period != entity.work_period:
            logger.info(
                "Changing work history period",
                extra={
                    "event_type": "work_history_field_change",
                    "entity_id": model.id,
                    "field": "work_period",
                    "old_value": model.work_period,
                    "new_value": entity.work_period
                }
            )

        if model.end_flag != entity.end_flag:
            logger.info(
                "Changing work history end flag",
                extra={
                    "event_type": "work_history_field_change",
                    "entity_id": model.id,
                    "field": "end_flag",
                    "old_value": model.end_flag,
                    "new_value": entity.end_flag
                }
            )

        # Update the model
        model.employee_id = entity.employee_id
        model.station_id = entity.workstation_id
        model.worked_date = entity.worked_date
        model.work_period = entity.work_period
        model.end_flag = entity.end_flag
        # We don't update the status field as it's not part of the WorkHistoryEntry entity
