"""add aro_assignments table

Revision ID: 228d94b108d2
Revises: c8f2a1b4d5e6
Create Date: 2025-06-02 14:47:29.828861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228d94b108d2'
down_revision: Union[str, None] = 'c8f2a1b4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__EFMigrationsHistory')
    op.create_unique_constraint(op.f('uq_employee_station_skills_id'), 'employee_station_skills', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_employee_station_skills_id'), 'employee_station_skills', type_='unique')
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name='PK___EFMigrationsHistory')
    )
    # ### end Alembic commands ###
