"""add aro_assignments table

Revision ID: 28f38a533018
Revises: 7693a0b424a3
Create Date: 2025-06-02 14:56:32.145810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f38a533018'
down_revision: Union[str, None] = '7693a0b424a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aro_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=False),
    sa.Column('to_team_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_aro_assignments_employee_id_employees')),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], name=op.f('fk_aro_assignments_from_team_id_teams')),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], name=op.f('fk_aro_assignments_to_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aro_assignments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aro_assignments')
    # ### end Alembic commands ###
