"""Initial schema

Revision ID: b8da5cc1614e
Revises: 
Create Date: 2025-05-28 11:52:35.683310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8da5cc1614e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('name', name=op.f('uq_employees_name'))
    )
    op.create_table('line_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_types')),
    sa.UniqueConstraint('name', name=op.f('uq_line_types_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name='_role_name_uc')
    )
    op.create_table('watcher_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watcher_heartbeat'))
    )
    op.create_table('employee_availability',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_call_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_aro', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_availability_employee_id_employees')),
    sa.PrimaryKeyConstraint('employee_id', 'date', 'period', name=op.f('pk_employee_availability'))
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_groups_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_teams_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('periods_per_day', sa.Integer(), nullable=False),
    sa.Column('call_ins', sa.JSON(), nullable=True),
    sa.Column('offline', sa.JSON(), nullable=True),
    sa.Column('force_complete', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_schedules_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index('idx_team_date_status', 'schedules', ['team_id', 'start_date', 'status'], unique=False)
    op.create_index(op.f('ix_schedules_created_at'), 'schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedules_start_date'), 'schedules', ['start_date'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('ix_schedules_task_id'), 'schedules', ['task_id'], unique=False)
    op.create_index(op.f('ix_schedules_team_id'), 'schedules', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_team_members_employee_id_employees')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'employee_id', name='_team_member_uc')
    )
    op.create_table('workstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('line_type_id', sa.Integer(), nullable=False),
    sa.Column('is_loading_job', sa.Boolean(), nullable=False),
    sa.Column('is_heavy_job', sa.Boolean(), nullable=False),
    sa.Column('is_key_skill_job', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_type_id'], ['line_types.id'], name=op.f('fk_workstations_line_type_id_line_types')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_workstations_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workstations')),
    sa.UniqueConstraint('name', name=op.f('uq_workstations_name'))
    )
    op.create_table('employee_station_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('certified', 'in_training', 'expired', 'flagged', 'banned', name='skill_status_enum'), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_station_skills_employee_id_employees')),
    sa.ForeignKeyConstraint(['station_id'], ['workstations.id'], name=op.f('fk_employee_station_skills_station_id_workstations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_station_skills')),
    sa.UniqueConstraint('id', name=op.f('uq_employee_station_skills_id'))
    )
    op.create_table('employee_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('required_training', sa.Boolean(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_training_employee_id_employees')),
    sa.ForeignKeyConstraint(['station_id'], ['workstations.id'], name=op.f('fk_employee_training_station_id_workstations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_training'))
    )
    op.create_table('employee_work_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('worked_date', sa.Date(), nullable=False),
    sa.Column('work_period', sa.Integer(), nullable=False),
    sa.Column('end_flag', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('is_temporary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_work_history_employee_id_employees')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_employee_work_history_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['station_id'], ['workstations.id'], name=op.f('fk_employee_work_history_station_id_workstations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_work_history'))
    )
    op.create_table('employee_workstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('last_worked_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_workstations_employee_id_employees')),
    sa.ForeignKeyConstraint(['station_id'], ['workstations.id'], name=op.f('fk_employee_workstations_station_id_workstations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_workstations'))
    )
    op.create_table('team_member_roles',
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_team_member_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], name=op.f('fk_team_member_roles_team_member_id_team_members')),
    sa.PrimaryKeyConstraint('team_member_id', 'role_id', name=op.f('pk_team_member_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member_roles')
    op.drop_table('employee_workstations')
    op.drop_table('employee_work_history')
    op.drop_table('employee_training')
    op.drop_table('employee_station_skills')
    op.drop_table('workstations')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_schedules_team_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_task_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_start_date'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_created_at'), table_name='schedules')
    op.drop_index('idx_team_date_status', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('groups')
    op.drop_table('employee_availability')
    op.drop_table('watcher_heartbeat')
    op.drop_table('roles')
    op.drop_table('line_types')
    op.drop_table('employees')
    op.drop_table('departments')
    # ### end Alembic commands ###
