"""Initial schema

Revision ID: c75ee1bbbfc0
Revises: 
Create Date: 2025-05-19 00:14:18.537371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75ee1bbbfc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_station_skills')
    op.drop_table('watcher_heartbeat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watcher_heartbeat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_run', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_watcher_heartbeat')
    )
    op.create_table('employee_station_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('station_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('last_verified', sa.DATE(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_employee_station_skills_employee_id_employees'),
    sa.ForeignKeyConstraint(['station_id'], ['workstations.id'], name='fk_employee_station_skills_station_id_workstations'),
    sa.PrimaryKeyConstraint('id', name='pk_employee_station_skills'),
    sa.UniqueConstraint('id', name='uq_employee_station_skills_id')
    )
    # ### end Alembic commands ###
