"""Initial schema

Revision ID: c75ee1bbbfc0
Revises: 
Create Date: 2025-05-19 00:14:18.537371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75ee1bbbfc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create base tables for the application

    # Create employees table
    op.create_table(
        'employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create teams table
    op.create_table(
        'teams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create workstations table
    op.create_table(
        'workstations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create groups table
    op.create_table(
        'groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create employee_work_history table
    op.create_table(
        'employee_work_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('workstation_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('period', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
        sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create employee_workstation table (for qualifications)
    op.create_table(
        'employee_workstation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('workstation_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
        sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create employee_availability table
    op.create_table(
        'employee_availability',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('period', sa.Integer(), nullable=True),
        sa.Column('is_partial', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('is_call_in', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('is_aro', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('is_offline', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create roles table
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Create team_member table
    op.create_table(
        'team_members',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Create team_member_roles association table
    op.create_table(
        'team_member_roles',
        sa.Column('team_member_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id']),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id']),
        sa.PrimaryKeyConstraint('team_member_id', 'role_id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watcher_heartbeat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_run', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_watcher_heartbeat')
    )
    op.create_table('employee_station_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('station_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('last_verified', sa.DATE(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_employee_station_skills_employee_id_employees'),
    sa.ForeignKeyConstraint(['station_id'], ['workstations.id'], name='fk_employee_station_skills_station_id_workstations'),
    sa.PrimaryKeyConstraint('id', name='pk_employee_station_skills'),
    sa.UniqueConstraint('id', name='uq_employee_station_skills_id')
    )
    # ### end Alembic commands ###
