"""Add team_aros table

Revision ID: da795f9b121b
Revises: 03472447cb7a
Create Date: 2025-06-05 16:30:38.428083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da795f9b121b'
down_revision: Union[str, None] = '03472447cb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_employee_station_skills_id'), 'employee_station_skills', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_employee_station_skills_id'), 'employee_station_skills', type_='unique')
    # ### end Alembic commands ###
