from typing import Optional, List, Generator
from datetime import datetime
from contextlib import contextmanager
from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError

from domain.value_objects.work_assignment import WorkAssignment
from domain.value_objects.schedule_period import SchedulePeriod
from domain.models.EmployeeWorkHistoryModel import EmployeeWorkHistoryModel
from domain.models.EmployeeModel import EmployeeModel
from domain.models.WorkstationModel import WorkstationModel
from domain.repositories.interfaces.assignment_repository import AssignmentRepositoryInterface
from domain.repositories.implementations.base_sqlalchemy_repository import BaseSqlAlchemyRepository
from infrastructure.exceptions import RepositoryError
from utilities.secure_logging import sanitize_exception
from utilities.logging_factory import get_logger


class SqlAlchemyAssignmentRepository(BaseSqlAlchemyRepository[WorkAssignment, EmployeeWorkHistoryModel], AssignmentRepositoryInterface):
    """
    SQLAlchemy implementation of the AssignmentRepository interface.
    """

    def __init__(self, session: Session):
        """
        Initialize the repository with a SQLAlchemy session.

        Args:
            session: The SQLAlchemy session to use for database operations.
        """
        super().__init__(session, EmployeeWorkHistoryModel, WorkAssignment)
        self.logger = get_logger("heijunka.repositories.assignment")
        self.rate_limited_logger = get_logger("heijunka.repositories.assignment", rate_limit=True)

    @contextmanager
    def session_scope(self) -> Generator[Session, None, None]:
        """
        Provide a transactional scope around a series of operations.

        Yields:
            The SQLAlchemy session.
        """
        try:
            yield self._session
            self._session.commit()
        except SQLAlchemyError as e:
            self._session.rollback()
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Database operation failed: {error_msg}",
                extra={
                    "event_type": "database_error",
                    "error_type": type(e).__name__,
                    "repository": "assignment"
                }
            )
            raise RepositoryError(f"Database error: {error_msg}")
        except Exception as e:
            self._session.rollback()
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Unexpected error in assignment repository: {error_msg}",
                extra={
                    "event_type": "unexpected_error",
                    "error_type": type(e).__name__,
                    "repository": "assignment"
                }
            )
            raise RepositoryError(f"Repository error: {error_msg}")

    def delete_existing_entries_for_date(self, date) -> int:
        """
        Delete all existing work history entries for a specific date.

        This method only deletes entries that were generated by the scheduler and are not temporary.

        Args:
            date: The date for which to delete entries.

        Returns:
            The number of entries deleted.
        """
        self.logger.info(
            f"Deleting existing work history entries for date: {date}",
            extra={
                "event_type": "work_history_entries_deletion",
                "date": date.isoformat() if hasattr(date, 'isoformat') else str(date)
            }
        )

        try:
            with self.session_scope() as session:
                # Find all entries for the given date that were generated by the scheduler and are not temporary
                query = session.query(EmployeeWorkHistoryModel).filter(
                    EmployeeWorkHistoryModel.worked_date == date,
                    EmployeeWorkHistoryModel.is_generated == True,
                    EmployeeWorkHistoryModel.is_temporary == False
                )

                # Get the count before deleting
                count = query.count()

                self.logger.info(
                    f"Found {count} entries to delete for date: {date}",
                    extra={
                        "event_type": "work_history_entries_found",
                        "date": date.isoformat() if hasattr(date, 'isoformat') else str(date),
                        "count": count
                    }
                )

                if count > 0:
                    # Delete the entries
                    query.delete(synchronize_session='fetch')

                    # Flush the session to ensure the delete operation is executed
                    session.flush()

                    self.logger.info(
                        f"Successfully deleted {count} work history entries for date: {date}",
                        extra={
                            "event_type": "work_history_entries_deletion_success",
                            "date": date.isoformat() if hasattr(date, 'isoformat') else str(date),
                            "count": count
                        }
                    )
                else:
                    self.logger.info(
                        f"No work history entries found to delete for date: {date}",
                        extra={
                            "event_type": "work_history_entries_deletion_skipped",
                            "date": date.isoformat() if hasattr(date, 'isoformat') else str(date),
                            "reason": "no_entries_found"
                        }
                    )

                return count
        except RepositoryError:
            # This will be caught and logged by session_scope
            raise
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error deleting work history entries for date: {error_msg}",
                extra={
                    "event_type": "work_history_entries_deletion_error",
                    "date": date.isoformat() if hasattr(date, 'isoformat') else str(date),
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error deleting work history entries: {error_msg}")

    def save_all(self, assignments: List[WorkAssignment]) -> bool:
        """
        Save a list of work assignments.

        This method first deletes any existing entries for the dates in the assignments
        to avoid duplicate schedules.

        Args:
            assignments: The list of work assignments to save.

        Returns:
            True if all assignments were saved successfully, False otherwise.
        """
        if not assignments:
            self.logger.info(
                "No assignments to save",
                extra={
                    "event_type": "assignments_save_skipped",
                    "reason": "no_assignments"
                }
            )
            return True

        self.logger.info(
            f"Saving {len(assignments)} work assignments",
            extra={
                "event_type": "assignments_save",
                "assignment_count": len(assignments)
            }
        )

        try:
            with self.session_scope() as session:
                # Group assignments by date
                dates = set(assignment.period.date for assignment in assignments)

                self.logger.info(
                    f"Assignments span {len(dates)} unique dates",
                    extra={
                        "event_type": "assignments_dates",
                        "date_count": len(dates)
                    }
                )

                # Delete existing entries for each date
                for date in dates:
                    deleted_count = self.delete_existing_entries_for_date(date)

                # Expire all objects in the session to clear the identity map
                session.expire_all()

                # Add new assignments
                for assignment in assignments:
                    # Convert domain entity to model
                    model = EmployeeWorkHistoryModel(
                        employee_id=assignment.employee.id,
                        station_id=assignment.workstation.id,
                        schedule_id=getattr(assignment, 'schedule_id', None),  # Include schedule_id if available
                        worked_date=assignment.period.date,
                        work_period=assignment.period.period,
                        end_flag=False,  # Default value
                        is_generated=True  # This is generated by the scheduler
                    )
                    session.add(model)

                    self.rate_limited_logger.debug(
                        f"Added assignment for employee {assignment.employee.id} at workstation {assignment.workstation.id}",
                        event_type="assignment_added",
                        identifier=f"{assignment.employee.id}_{assignment.workstation.id}_{assignment.period.date}_{assignment.period.period}",
                        extra={
                            "employee_id": assignment.employee.id,
                            "workstation_id": assignment.workstation.id,
                            "date": assignment.period.date.isoformat() if hasattr(assignment.period.date, 'isoformat') else str(assignment.period.date),
                            "period": assignment.period.period
                        }
                    )

                self.logger.info(
                    f"Successfully saved {len(assignments)} work assignments",
                    extra={
                        "event_type": "assignments_save_success",
                        "assignment_count": len(assignments)
                    }
                )
                return True
        except RepositoryError:
            # This will be caught and logged by session_scope
            raise
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error saving work assignments: {error_msg}",
                extra={
                    "event_type": "assignments_save_error",
                    "assignment_count": len(assignments) if assignments else 0,
                    "error_type": type(e).__name__
                }
            )
            return False

    def get_by_employee_id(self, employee_id: int) -> List[WorkAssignment]:
        """
        Retrieve all assignments for a specific employee.

        Args:
            employee_id: The ID of the employee.

        Returns:
            A list of work assignments for the employee.
        """
        self.logger.info(
            f"Retrieving assignments for employee ID: {employee_id}",
            extra={
                "event_type": "assignments_lookup",
                "lookup_type": "employee_id",
                "employee_id": employee_id
            }
        )

        try:
            models = self._session.query(EmployeeWorkHistoryModel).filter(
                EmployeeWorkHistoryModel.employee_id == employee_id
            ).all()

            assignment_count = len(models)
            self.logger.info(
                f"Found {assignment_count} assignments for employee ID: {employee_id}",
                extra={
                    "event_type": "assignments_lookup_success",
                    "lookup_type": "employee_id",
                    "employee_id": employee_id,
                    "assignment_count": assignment_count
                }
            )

            return [self._to_domain(model) for model in models]
        except SQLAlchemyError as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error retrieving assignments for employee: {error_msg}",
                extra={
                    "event_type": "assignments_lookup_error",
                    "lookup_type": "employee_id",
                    "employee_id": employee_id,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Database error while retrieving assignments: {error_msg}")
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Unexpected error retrieving assignments for employee: {error_msg}",
                extra={
                    "event_type": "assignments_lookup_error",
                    "lookup_type": "employee_id",
                    "employee_id": employee_id,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error retrieving assignments: {error_msg}")

    def get_by_workstation_id(self, workstation_id: int) -> List[WorkAssignment]:
        """
        Retrieve all assignments for a specific workstation.

        Args:
            workstation_id: The ID of the workstation.

        Returns:
            A list of work assignments for the workstation.
        """
        self.logger.info(
            f"Retrieving assignments for workstation ID: {workstation_id}",
            extra={
                "event_type": "assignments_lookup",
                "lookup_type": "workstation_id",
                "workstation_id": workstation_id
            }
        )

        try:
            models = self._session.query(EmployeeWorkHistoryModel).filter(
                EmployeeWorkHistoryModel.station_id == workstation_id
            ).all()

            assignment_count = len(models)
            self.logger.info(
                f"Found {assignment_count} assignments for workstation ID: {workstation_id}",
                extra={
                    "event_type": "assignments_lookup_success",
                    "lookup_type": "workstation_id",
                    "workstation_id": workstation_id,
                    "assignment_count": assignment_count
                }
            )

            return [self._to_domain(model) for model in models]
        except SQLAlchemyError as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error retrieving assignments for workstation: {error_msg}",
                extra={
                    "event_type": "assignments_lookup_error",
                    "lookup_type": "workstation_id",
                    "workstation_id": workstation_id,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Database error while retrieving assignments: {error_msg}")
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Unexpected error retrieving assignments for workstation: {error_msg}",
                extra={
                    "event_type": "assignments_lookup_error",
                    "lookup_type": "workstation_id",
                    "workstation_id": workstation_id,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error retrieving assignments: {error_msg}")

    def get_by_schedule_id(self, schedule_id: int) -> List[WorkAssignment]:
        """
        Retrieve all assignments for a specific schedule.

        Args:
            schedule_id: The ID of the schedule.

        Returns:
            A list of work assignments for the schedule.
        """
        self.logger.info(
            f"Retrieving assignments for schedule ID: {schedule_id}",
            extra={
                "event_type": "assignments_lookup",
                "lookup_type": "schedule_id",
                "schedule_id": schedule_id
            }
        )

        try:
            models = self._session.query(EmployeeWorkHistoryModel).filter(
                EmployeeWorkHistoryModel.schedule_id == schedule_id
            ).all()

            assignment_count = len(models)
            self.logger.info(
                f"Found {assignment_count} assignments for schedule ID: {schedule_id}",
                extra={
                    "event_type": "assignments_lookup_success",
                    "lookup_type": "schedule_id",
                    "schedule_id": schedule_id,
                    "assignment_count": assignment_count
                }
            )

            return [self._to_domain(model) for model in models]
        except SQLAlchemyError as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error retrieving assignments for schedule: {error_msg}",
                extra={
                    "event_type": "assignments_lookup_error",
                    "lookup_type": "schedule_id",
                    "schedule_id": schedule_id,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Database error while retrieving assignments: {error_msg}")
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Unexpected error retrieving assignments for schedule: {error_msg}",
                extra={
                    "event_type": "assignments_lookup_error",
                    "lookup_type": "schedule_id",
                    "schedule_id": schedule_id,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error retrieving assignments: {error_msg}")

    def _to_domain(self, model: EmployeeWorkHistoryModel) -> WorkAssignment:
        """
        Convert a SQLAlchemy model to a domain entity.

        Args:
            model: The SQLAlchemy model to convert.

        Returns:
            The domain entity.
        """
        try:
            self.logger.debug(
                "Converting work history model to domain entity",
                extra={
                    "event_type": "model_to_domain_conversion",
                    "entity_id": model.id,
                    "employee_id": model.employee_id,
                    "station_id": model.station_id
                }
            )

            # Fetch the related employee and workstation
            employee_model = self._session.query(EmployeeModel).get(model.employee_id)
            workstation_model = self._session.query(WorkstationModel).get(model.station_id)

            if not employee_model or not workstation_model:
                error_msg = f"Related entity not found for work history entry {model.id}"
                self.logger.error(
                    error_msg,
                    extra={
                        "event_type": "model_to_domain_conversion_error",
                        "entity_id": model.id,
                        "employee_id": model.employee_id,
                        "station_id": model.station_id,
                        "reason": "related_entity_not_found"
                    }
                )
                raise RepositoryError(error_msg)

            # Convert to domain entities
            employee = employee_model.to_domain()
            workstation = workstation_model.to_domain()

            # Create schedule period
            period = SchedulePeriod(date=model.worked_date, period=model.work_period)

            # Create work assignment
            assignment = WorkAssignment(
                employee=employee,
                workstation=workstation,
                period=period
            )

            # If the model has a schedule_id, add it to the assignment
            if hasattr(model, 'schedule_id') and model.schedule_id is not None:
                setattr(assignment, 'schedule_id', model.schedule_id)

            self.logger.debug(
                "Successfully converted work history model to domain entity",
                extra={
                    "event_type": "model_to_domain_conversion_success",
                    "entity_id": model.id
                }
            )

            return assignment
        except RepositoryError:
            # This will be logged by the code above
            raise
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error converting work history model to domain entity: {error_msg}",
                extra={
                    "event_type": "model_to_domain_conversion_error",
                    "entity_id": model.id if model else None,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error converting model to domain entity: {error_msg}")

    def _to_model(self, entity: WorkAssignment) -> EmployeeWorkHistoryModel:
        """
        Convert a domain entity to a SQLAlchemy model.

        Args:
            entity: The domain entity to convert.

        Returns:
            The SQLAlchemy model.
        """
        try:
            self.logger.debug(
                "Converting work assignment domain entity to model",
                extra={
                    "event_type": "domain_to_model_conversion",
                    "employee_id": entity.employee.id,
                    "workstation_id": entity.workstation.id,
                    "date": entity.period.date.isoformat() if hasattr(entity.period.date, 'isoformat') else str(entity.period.date),
                    "period": entity.period.period
                }
            )

            schedule_id = getattr(entity, 'schedule_id', None)

            model = EmployeeWorkHistoryModel(
                employee_id=entity.employee.id,
                station_id=entity.workstation.id,
                schedule_id=schedule_id,  # Include schedule_id if available
                worked_date=entity.period.date,
                work_period=entity.period.period,
                end_flag=False,  # Default value
                is_generated=True,  # This is generated by the scheduler
                is_temporary=False  # Default is not temporary
            )

            self.logger.debug(
                "Successfully converted work assignment domain entity to model",
                extra={
                    "event_type": "domain_to_model_conversion_success",
                    "employee_id": entity.employee.id,
                    "workstation_id": entity.workstation.id
                }
            )

            return model
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error converting work assignment domain entity to model: {error_msg}",
                extra={
                    "event_type": "domain_to_model_conversion_error",
                    "employee_id": entity.employee.id if entity and hasattr(entity, 'employee') and hasattr(entity.employee, 'id') else None,
                    "workstation_id": entity.workstation.id if entity and hasattr(entity, 'workstation') and hasattr(entity.workstation, 'id') else None,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error converting domain entity to model: {error_msg}")

    def create_temporary_assignment(self, employee_id: int, workstation_id: int, date, period: int, schedule_id: int = None) -> bool:
        """
        Create a temporary assignment for an employee at a workstation.

        This method is used when an employee temporarily takes over a station from another employee.

        Args:
            employee_id: The ID of the employee taking over the station.
            workstation_id: The ID of the workstation being taken over.
            date: The date of the assignment.
            period: The period of the day.
            schedule_id: Optional ID of the schedule this assignment belongs to.

        Returns:
            True if the assignment was created successfully, False otherwise.
        """
        self.logger.info(
            f"Creating temporary assignment for employee ID: {employee_id} at workstation ID: {workstation_id}",
            extra={
                "event_type": "temporary_assignment_creation",
                "employee_id": employee_id,
                "workstation_id": workstation_id,
                "date": date.isoformat() if hasattr(date, 'isoformat') else str(date),
                "period": period,
                "schedule_id": schedule_id
            }
        )

        try:
            with self.session_scope() as session:
                # Create a new model for the temporary assignment
                model = EmployeeWorkHistoryModel(
                    employee_id=employee_id,
                    station_id=workstation_id,
                    schedule_id=schedule_id,
                    worked_date=date,
                    work_period=period,
                    end_flag=False,  # Default value
                    is_generated=False,  # This is not generated by the scheduler
                    is_temporary=True  # This is a temporary assignment
                )
                session.add(model)

                self.logger.info(
                    "Successfully created temporary assignment",
                    extra={
                        "event_type": "temporary_assignment_creation_success",
                        "employee_id": employee_id,
                        "workstation_id": workstation_id,
                        "date": date.isoformat() if hasattr(date, 'isoformat') else str(date),
                        "period": period,
                        "schedule_id": schedule_id
                    }
                )
                return True
        except RepositoryError:
            # This will be caught and logged by session_scope
            raise
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error creating temporary assignment: {error_msg}",
                extra={
                    "event_type": "temporary_assignment_creation_error",
                    "employee_id": employee_id,
                    "workstation_id": workstation_id,
                    "date": date.isoformat() if hasattr(date, 'isoformat') else str(date),
                    "period": period,
                    "schedule_id": schedule_id,
                    "error_type": type(e).__name__
                }
            )
            return False

    def delete_by_schedule_id(self, schedule_id: int) -> bool:
        """
        Delete all assignments for a specific schedule.

        Args:
            schedule_id: ID of the schedule

        Returns:
            True if successful, False otherwise
        """
        self.logger.info(
            f"Deleting assignments for schedule ID: {schedule_id}",
            extra={
                "event_type": "assignments_deletion",
                "schedule_id": schedule_id
            }
        )

        try:
            with self.session_scope() as session:
                # First, count how many assignments will be deleted
                count = session.query(EmployeeWorkHistoryModel).filter(
                    EmployeeWorkHistoryModel.schedule_id == schedule_id
                ).count()

                self.logger.info(
                    f"Found {count} assignments to delete for schedule ID: {schedule_id}",
                    extra={
                        "event_type": "assignments_deletion_count",
                        "schedule_id": schedule_id,
                        "count": count
                    }
                )

                if count > 0:
                    # Delete the assignments
                    session.query(EmployeeWorkHistoryModel).filter(
                        EmployeeWorkHistoryModel.schedule_id == schedule_id
                    ).delete(synchronize_session='fetch')

                    self.logger.info(
                        f"Successfully deleted {count} assignments for schedule ID: {schedule_id}",
                        extra={
                            "event_type": "assignments_deletion_success",
                            "schedule_id": schedule_id,
                            "count": count
                        }
                    )
                else:
                    self.logger.info(
                        f"No assignments found to delete for schedule ID: {schedule_id}",
                        extra={
                            "event_type": "assignments_deletion_skipped",
                            "schedule_id": schedule_id,
                            "reason": "no_assignments_found"
                        }
                    )

                return True
        except RepositoryError:
            # This will be caught and logged by session_scope
            raise
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error deleting assignments for schedule: {error_msg}",
                extra={
                    "event_type": "assignments_deletion_error",
                    "schedule_id": schedule_id,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error deleting assignments for schedule {schedule_id}: {error_msg}")

    def _update_model(self, model: EmployeeWorkHistoryModel, entity: WorkAssignment) -> None:
        """
        Update a SQLAlchemy model with values from a domain entity.

        Args:
            model: The SQLAlchemy model to update.
            entity: The domain entity with updated values.
        """
        try:
            self.logger.debug(
                "Updating work history model from domain entity",
                extra={
                    "event_type": "work_history_model_update",
                    "entity_id": model.id,
                    "employee_id": model.employee_id,
                    "station_id": model.station_id
                }
            )

            # Check for significant changes and log them
            if model.employee_id != entity.employee.id:
                self.logger.info(
                    "Changing work history employee",
                    extra={
                        "event_type": "work_history_field_change",
                        "entity_id": model.id,
                        "field": "employee_id",
                        "old_value": model.employee_id,
                        "new_value": entity.employee.id
                    }
                )

            if model.station_id != entity.workstation.id:
                self.logger.info(
                    "Changing work history workstation",
                    extra={
                        "event_type": "work_history_field_change",
                        "entity_id": model.id,
                        "field": "station_id",
                        "old_value": model.station_id,
                        "new_value": entity.workstation.id
                    }
                )

            if model.worked_date != entity.period.date:
                self.logger.info(
                    "Changing work history date",
                    extra={
                        "event_type": "work_history_field_change",
                        "entity_id": model.id,
                        "field": "worked_date",
                        "old_value": model.worked_date.isoformat() if hasattr(model.worked_date, 'isoformat') else str(model.worked_date),
                        "new_value": entity.period.date.isoformat() if hasattr(entity.period.date, 'isoformat') else str(entity.period.date)
                    }
                )

            if model.work_period != entity.period.period:
                self.logger.info(
                    "Changing work history period",
                    extra={
                        "event_type": "work_history_field_change",
                        "entity_id": model.id,
                        "field": "work_period",
                        "old_value": model.work_period,
                        "new_value": entity.period.period
                    }
                )

            # Update the model
            model.employee_id = entity.employee.id
            model.station_id = entity.workstation.id
            model.worked_date = entity.period.date
            model.work_period = entity.period.period
            # We don't update end_flag, is_generated, or is_temporary as they are not part of the WorkAssignment entity

            # If the entity has a schedule_id, update it in the model
            if hasattr(entity, 'schedule_id') and entity.schedule_id is not None:
                if model.schedule_id != entity.schedule_id:
                    self.logger.info(
                        "Changing work history schedule",
                        extra={
                            "event_type": "work_history_field_change",
                            "entity_id": model.id,
                            "field": "schedule_id",
                            "old_value": model.schedule_id,
                            "new_value": entity.schedule_id
                        }
                    )
                model.schedule_id = entity.schedule_id

            self.logger.debug(
                "Successfully updated work history model",
                extra={
                    "event_type": "work_history_model_update_success",
                    "entity_id": model.id
                }
            )
        except Exception as e:
            error_msg = sanitize_exception(e)
            self.logger.error(
                f"Error updating work history model: {error_msg}",
                extra={
                    "event_type": "work_history_model_update_error",
                    "entity_id": model.id if model else None,
                    "error_type": type(e).__name__
                }
            )
            raise RepositoryError(f"Error updating model: {error_msg}")
