from typing import Optional, List
from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError

from domain.value_objects.work_assignment import WorkAssignment
from domain.value_objects.schedule_period import SchedulePeriod
from domain.models.EmployeeWorkHistoryModel import EmployeeWorkHistoryModel
from domain.models.EmployeeModel import EmployeeModel
from domain.models.WorkstationModel import WorkstationModel
from domain.repositories.interfaces.assignment_repository import AssignmentRepositoryInterface
from domain.repositories.implementations.base_sqlalchemy_repository import BaseSqlAlchemyRepository
from infrastructure.exceptions import RepositoryError


class SqlAlchemyAssignmentRepository(BaseSqlAlchemyRepository[WorkAssignment, EmployeeWorkHistoryModel], AssignmentRepositoryInterface):
    def __init__(self, session: Session):
        super().__init__(session, EmployeeWorkHistoryModel, WorkAssignment)

    def delete_existing_entries_for_date(self, date) -> int:
        """
        Delete all existing work history entries for a specific date.

        This method only deletes entries that were generated by the scheduler and are not temporary.

        Args:
            date: The date for which to delete entries.

        Returns:
            The number of entries deleted.
        """
        try:
            # Find all entries for the given date that were generated by the scheduler and are not temporary
            query = self._session.query(EmployeeWorkHistoryModel).filter(
                EmployeeWorkHistoryModel.worked_date == date,
                EmployeeWorkHistoryModel.is_generated == True,
                EmployeeWorkHistoryModel.is_temporary == False
            )

            # Get the count before deleting
            count = query.count()

            # Delete the entries
            query.delete(synchronize_session='fetch')

            # Flush the session to ensure the delete operation is executed
            self._session.flush()

            return count
        except SQLAlchemyError as e:
            self._session.rollback()
            raise RepositoryError(f"Database error while deleting existing entries: {str(e)}")

    def save_all(self, assignments: List[WorkAssignment]) -> bool:
        """
        Save a list of work assignments.

        This method first deletes any existing entries for the dates in the assignments
        to avoid duplicate schedules.

        Args:
            assignments: The list of work assignments to save.

        Returns:
            True if all assignments were saved successfully, False otherwise.
        """
        if not assignments:
            return True

        try:
            # Group assignments by date
            dates = set(assignment.period.date for assignment in assignments)

            # Delete existing entries for each date
            for date in dates:
                deleted_count = self.delete_existing_entries_for_date(date)

            # Expire all objects in the session to clear the identity map
            self._session.expire_all()

            # Add new assignments
            for assignment in assignments:
                # Convert domain entity to model
                model = EmployeeWorkHistoryModel(
                    employee_id=assignment.employee.id,
                    station_id=assignment.workstation.id,
                    schedule_id=getattr(assignment, 'schedule_id', None),  # Include schedule_id if available
                    worked_date=assignment.period.date,
                    work_period=assignment.period.period,
                    end_flag=False,  # Default value
                    is_generated=True  # This is generated by the scheduler
                )
                self._session.add(model)

            self._session.commit()
            return True
        except SQLAlchemyError as e:
            self._session.rollback()
            raise RepositoryError(f"Database error while saving assignments: {str(e)}")
        except Exception as e:
            self._session.rollback()
            return False

    def get_by_employee_id(self, employee_id: int) -> List[WorkAssignment]:
        """
        Retrieve all assignments for a specific employee.

        Args:
            employee_id: The ID of the employee.

        Returns:
            A list of work assignments for the employee.
        """
        try:
            models = self._session.query(EmployeeWorkHistoryModel).filter(
                EmployeeWorkHistoryModel.employee_id == employee_id
            ).all()

            return [self._to_domain(model) for model in models]
        except SQLAlchemyError as e:
            raise RepositoryError(f"Database error while retrieving assignments: {str(e)}")

    def get_by_workstation_id(self, workstation_id: int) -> List[WorkAssignment]:
        """
        Retrieve all assignments for a specific workstation.

        Args:
            workstation_id: The ID of the workstation.

        Returns:
            A list of work assignments for the workstation.
        """
        try:
            models = self._session.query(EmployeeWorkHistoryModel).filter(
                EmployeeWorkHistoryModel.station_id == workstation_id
            ).all()

            return [self._to_domain(model) for model in models]
        except SQLAlchemyError as e:
            raise RepositoryError(f"Database error while retrieving assignments: {str(e)}")

    def get_by_schedule_id(self, schedule_id: int) -> List[WorkAssignment]:
        """
        Retrieve all assignments for a specific schedule.

        Args:
            schedule_id: The ID of the schedule.

        Returns:
            A list of work assignments for the schedule.
        """
        try:
            models = self._session.query(EmployeeWorkHistoryModel).filter(
                EmployeeWorkHistoryModel.schedule_id == schedule_id
            ).all()

            return [self._to_domain(model) for model in models]
        except SQLAlchemyError as e:
            raise RepositoryError(f"Database error while retrieving assignments: {str(e)}")

    def _to_domain(self, model: EmployeeWorkHistoryModel) -> WorkAssignment:
        """Convert a SQLAlchemy model to a domain entity."""
        # Fetch the related employee and workstation
        employee_model = self._session.query(EmployeeModel).get(model.employee_id)
        workstation_model = self._session.query(WorkstationModel).get(model.station_id)

        if not employee_model or not workstation_model:
            raise RepositoryError(f"Related entity not found for work history entry {model.id}")

        # Convert to domain entities
        employee = employee_model.to_domain()
        workstation = workstation_model.to_domain()

        # Create schedule period
        period = SchedulePeriod(date=model.worked_date, period=model.work_period)

        # Create work assignment
        return WorkAssignment(
            employee=employee,
            workstation=workstation,
            period=period
        )

    def _to_model(self, entity: WorkAssignment) -> EmployeeWorkHistoryModel:
        """Convert a domain entity to a SQLAlchemy model."""
        return EmployeeWorkHistoryModel(
            employee_id=entity.employee.id,
            station_id=entity.workstation.id,
            schedule_id=getattr(entity, 'schedule_id', None),  # Include schedule_id if available
            worked_date=entity.period.date,
            work_period=entity.period.period,
            end_flag=False,  # Default value
            is_generated=True,  # This is generated by the scheduler
            is_temporary=False  # Default is not temporary
        )

    def create_temporary_assignment(self, employee_id: int, workstation_id: int, date, period: int, schedule_id: int = None) -> bool:
        """
        Create a temporary assignment for an employee at a workstation.

        This method is used when an employee temporarily takes over a station from another employee.

        Args:
            employee_id: The ID of the employee taking over the station.
            workstation_id: The ID of the workstation being taken over.
            date: The date of the assignment.
            period: The period of the day.
            schedule_id: Optional ID of the schedule this assignment belongs to.

        Returns:
            True if the assignment was created successfully, False otherwise.
        """
        try:
            # Create a new model for the temporary assignment
            model = EmployeeWorkHistoryModel(
                employee_id=employee_id,
                station_id=workstation_id,
                schedule_id=schedule_id,
                worked_date=date,
                work_period=period,
                end_flag=False,  # Default value
                is_generated=False,  # This is not generated by the scheduler
                is_temporary=True  # This is a temporary assignment
            )
            self._session.add(model)
            self._session.commit()
            return True
        except SQLAlchemyError as e:
            self._session.rollback()
            raise RepositoryError(f"Database error while creating temporary assignment: {str(e)}")
        except Exception as e:
            self._session.rollback()
            return False

    def _update_model(self, model: EmployeeWorkHistoryModel, entity: WorkAssignment) -> None:
        """Update a SQLAlchemy model with values from a domain entity."""
        model.employee_id = entity.employee.id
        model.station_id = entity.workstation.id
        model.worked_date = entity.period.date
        model.work_period = entity.period.period
        # We don't update end_flag, is_generated, or is_temporary as they are not part of the WorkAssignment entity
