# heijunka/domain/entities/team.py
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from datetime import date

from domain.entities.team_member import TeamMember
from domain.events import (
    DomainEvent, TeamMemberAdded, TeamMemberRemoved, 
    WorkstationAddedToTeam, WorkstationRemovedFromTeam
)


@dataclass
class Team:
    id: Optional[int]
    name: str
    description: str = ""
    _workstations: List["Workstation"] = field(default_factory=list, repr=False)
    _team_members: List[TeamMember] = field(default_factory=list, repr=False)
    _domain_events: List[DomainEvent] = field(default_factory=list, repr=False)

    def __post_init__(self):
        """Initialize collections if they are None."""
        if self._workstations is None:
            self._workstations = []
        if self._team_members is None:
            self._team_members = []
        if self._domain_events is None:
            self._domain_events = []

    @classmethod
    def create(cls, name: str, description: str = "") -> 'Team':
        """
        Creates a new Team entity.
        Note: This doesn't persist the team - that's the responsibility of the repository.

        Args:
            name: The name of the team
            description: Optional description of the team

        Returns:
            A new Team instance
        """
        # The ID will be generated by the persistence layer when the entity is saved
        return cls(
            id=None,  # This will be handled by the persistence layer
            name=name,
            description=description
        )

    @property
    def members(self) -> List["Employee"]:
        """Get a list of Employee objects derived from team_members."""
        result = []
        for team_member in self._team_members:
            if team_member.employee:
                result.append(team_member.employee)
        return result

    @property
    def workstations(self) -> List["Workstation"]:
        """Get a copy of the workstations list to prevent direct modification."""
        return self._workstations.copy()

    @property
    def team_members(self) -> List[TeamMember]:
        """Get a copy of the team members list to prevent direct modification."""
        return self._team_members.copy()

    @property
    def domain_events(self) -> List[DomainEvent]:
        """Get a copy of the domain events list."""
        return self._domain_events.copy()

    def clear_domain_events(self) -> None:
        """Clear all domain events after they've been processed."""
        self._domain_events.clear()

    def register_domain_event(self, event: DomainEvent) -> None:
        """Register a domain event."""
        self._domain_events.append(event)

    def add_member(self, employee: "Employee") -> bool:
        """
        Add an employee to the team.

        Args:
            employee: The employee to add.

        Returns:
            True if the employee was added, False if already a member.
        """
        # Check if the employee is already a member
        for team_member in self._team_members:
            if team_member.employee_id == employee.id:
                return False  # Already a member

        team_member = TeamMember(
            team_member_id=None,  # Let repository set this when saving
            team_id=self.id,
            employee_id=employee.id,
            employee=employee
        )
        self._team_members.append(team_member)

        # Register the domain event
        self.register_domain_event(TeamMemberAdded(self.id, employee.id, roles=[]))

        return True

    def remove_member(self, employee_id: int) -> bool:
        """
        Remove an employee from the team.

        Args:
            employee_id: The ID of the employee to remove.

        Returns:
            True if the employee was removed, False if not a member.
        """
        # Find the team member
        for i, team_member in enumerate(self._team_members):
            if team_member.employee_id == employee_id:
                # Remove the team member
                self._team_members.pop(i)

                # Register the domain event
                self.register_domain_event(TeamMemberRemoved(self.id, employee_id))

                return True

        return False

    def add_workstation(self, workstation: "Workstation") -> bool:
        """
        Add a workstation to the team.

        Args:
            workstation: The workstation to add.

        Returns:
            True if the workstation was added, False if already assigned.
        """
        # Check if the workstation is already assigned to the team
        for ws in self._workstations:
            if ws.id == workstation.id:
                return False  # Already assigned

        # Add the workstation to the team
        self._workstations.append(workstation)

        # Update the workstation's team_id
        workstation.team_id = self.id

        # Register the domain event
        self.register_domain_event(WorkstationAddedToTeam(self.id, workstation.id))

        return True

    def remove_workstation(self, workstation_id: int) -> bool:
        """
        Remove a workstation from the team.

        Args:
            workstation_id: The ID of the workstation to remove.

        Returns:
            True if the workstation was removed, False if not assigned.
        """
        # Find the workstation in the workstations list
        for i, ws in enumerate(self._workstations):
            if ws.id == workstation_id:
                # Remove the workstation from the workstations list
                workstation = self._workstations.pop(i)

                # Update the workstation's team_id
                workstation.team_id = None

                # Register the domain event
                self.register_domain_event(WorkstationRemovedFromTeam(self.id, workstation_id))

                return True

        return False

    def get_member_by_id(self, employee_id: int) -> Optional["Employee"]:
        """
        Get a team member by employee ID.

        Args:
            employee_id: The ID of the employee to find.

        Returns:
            The employee if found, None otherwise.
        """
        for team_member in self._team_members:
            if team_member.employee_id == employee_id:
                return team_member.employee
        return None

    def get_workstation_by_id(self, workstation_id: int) -> Optional["Workstation"]:
        """
        Get a workstation by ID.

        Args:
            workstation_id: The ID of the workstation to find.

        Returns:
            The workstation if found, None otherwise.
        """
        for ws in self._workstations:
            if ws.id == workstation_id:
                return ws
        return None

    def get_team_member_by_employee_id(self, employee_id: int) -> Optional[TeamMember]:
        """
        Get a TeamMember entity by employee ID.

        Args:
            employee_id: The ID of the employee to find.

        Returns:
            The TeamMember entity if found, None otherwise.
        """
        for team_member in self._team_members:
            if team_member.employee_id == employee_id:
                return team_member
        return None

    def assign_role_to_member(self, employee_id: int, role_name: str) -> bool:
        """
        Assign a role to a team member.

        Args:
            employee_id: The ID of the employee.
            role_name: The name of the role to assign.

        Returns:
            True if the role was assigned, False if the employee is not a member
            or already has the role.
        """
        team_member = self.get_team_member_by_employee_id(employee_id)
        if not team_member:
            return False

        return team_member.add_role(role_name)

    def remove_role_from_member(self, employee_id: int, role_name: str) -> bool:
        """
        Remove a role from a team member.

        Args:
            employee_id: The ID of the employee.
            role_name: The name of the role to remove.

        Returns:
            True if the role was removed, False if the employee is not a member
            or doesn't have the role.
        """
        team_member = self.get_team_member_by_employee_id(employee_id)
        if not team_member:
            return False

        return team_member.remove_role(role_name)

    def get_member_by_name(self, name: str) -> Optional["Employee"]:
        """
        Get a team member by name.

        Args:
            name: The name of the employee to find.

        Returns:
            The employee if found, None otherwise.
        """
        for team_member in self._team_members:
            if team_member.employee and team_member.employee.name == name:
                return team_member.employee
        return None

    def get_workstation_by_name(self, name: str) -> Optional["Workstation"]:
        """
        Get a workstation by name.

        Args:
            name: The name of the workstation to find.

        Returns:
            The workstation if found, None otherwise.
        """
        for ws in self._workstations:
            if ws.name == name:
                return ws
        return None

    def has_member_with_role(self, employee_id: int, role_name: str) -> bool:
        """
        Check if a team member has a specific role.

        Args:
            employee_id: The ID of the employee to check.
            role_name: The name of the role to check.

        Returns:
            True if the member has the role, False otherwise.
        """
        team_member = self.get_team_member_by_employee_id(employee_id)
        if not team_member:
            return False
        return team_member.has_role(role_name)

    def get_members_with_role(self, role_name: str) -> List["Employee"]:
        """
        Get all team members with a specific role.

        Args:
            role_name: The name of the role to check.

        Returns:
            A list of employees with the specified role.
        """
        members_with_role = []
        for team_member in self._team_members:
            if team_member.has_role(role_name):
                employee = self.get_member_by_id(team_member.employee_id)
                if employee:
                    members_with_role.append(employee)
        return members_with_role

    def update_properties(self, name: Optional[str] = None, description: Optional[str] = None) -> None:
        """
        Update the team's properties.

        Args:
            name: The new name for the team (optional).
            description: The new description for the team (optional).
        """
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description

    def has_workstation(self, workstation_id: int) -> bool:
        """
        Check if a workstation is part of the team.

        Args:
            workstation_id: The ID of the workstation to check.

        Returns:
            True if the workstation is part of the team, False otherwise.
        """
        return self.get_workstation_by_id(workstation_id) is not None

    def has_member(self, employee_id: int) -> bool:
        """
        Check if an employee is a member of the team.

        Args:
            employee_id: The ID of the employee to check.

        Returns:
            True if the employee is a member of the team, False otherwise.
        """
        return self.get_member_by_id(employee_id) is not None

    def get_members_with_qualification(self, qualification: str) -> List["Employee"]:
        """
        Get all team members with a specific qualification.

        Args:
            qualification: The qualification to check for.

        Returns:
            A list of employees with the specified qualification.
        """
        qualified_members = []
        for team_member in self._team_members:
            employee = team_member.employee
            if employee and hasattr(employee, 'qualifications') and qualification in employee.qualifications:
                qualified_members.append(employee)
        return qualified_members

    def get_statistics(self) -> Dict[str, Any]:
        """
        Calculate and return statistics about the team.

        Returns:
            A dictionary containing various team statistics:
            - member_count: Total number of team members
            - active_member_count: Number of active team members
            - workstation_count: Total number of workstations
            - qualification_counts: Dictionary mapping qualification names to counts
            - role_counts: Dictionary mapping role names to counts
        """
        stats = {
            "member_count": len(self._team_members),
            "workstation_count": len(self._workstations),
            "qualification_counts": {},
            "role_counts": {}
        }

        # Count active members
        active_members = [tm for tm in self._team_members 
                         if tm.employee and hasattr(tm.employee, 'is_active') and tm.employee.is_active]
        stats["active_member_count"] = len(active_members)

        # Count qualifications
        for team_member in self._team_members:
            if team_member.employee and hasattr(team_member.employee, 'qualifications'):
                for qual in team_member.employee.qualifications:
                    if qual in stats["qualification_counts"]:
                        stats["qualification_counts"][qual] += 1
                    else:
                        stats["qualification_counts"][qual] = 1

        # Count roles
        for team_member in self._team_members:
            for role in team_member.roles:
                if role in stats["role_counts"]:
                    stats["role_counts"][role] += 1
                else:
                    stats["role_counts"][role] = 1

        return stats

    def get_available_members(self, date_obj: date, period: int, call_ins: List[str] = None, offline: Dict[str, List[int]] = None) -> List["Employee"]:
        """
        Get all team members available for a specific date and period.

        Args:
            date_obj: The date to check availability for
            period: The period of the day to check (1-4 typically)
            call_ins: Optional list of employee names who called in (unavailable)
            offline: Optional dictionary mapping employee names to lists of periods they are offline

        Returns:
            A list of available employees
        """
        available_members = []

        # Start with all active members
        for team_member in self._team_members:
            employee = team_member.employee
            if not employee or not hasattr(employee, 'is_active') or not employee.is_active:
                continue

            # Check if the member called in
            if call_ins and employee.name in call_ins:
                continue

            # Check if the member is offline for this period
            if offline and employee.name in offline and period in offline[employee.name]:
                continue

            # Check if the member is available for this period
            if hasattr(employee, 'is_available_for_period') and not employee.is_available_for_period(date_obj, period):
                continue

            # If we got here, the member is available
            available_members.append(employee)

        return available_members

    def validate(self) -> None:
        """
        Validates the team entity.
        Raises ValueError if validation fails.
        """
        if not self.name:
            raise ValueError("Team name cannot be empty")
        if len(self.name) > 100:  # Example validation rule
            raise ValueError("Team name cannot be longer than 100 characters")
